django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("library.urls"))

]

library/urls.py
from django.urls import path

from .views import (HomePageView, GenreListView, AuthorListView, PublicationListView, CopiesListView, AuthorCreateView, GenreCreateView,
                    PublicationCreateView, CopyCreateView, PublicationDetailView, AuthorDetailView, GenreDetailView, CopiesDetailView,
                    PublicationUpdateView, AuthorUpdateView, GenreUpdateView, CopyUpdateView,
                    PublicationDeleteView, AuthorDeleteView, GenreDeleteView, CopyDeleteView)

urlpatterns = [
    path("detailcopy/<int:pk>/delete", CopyDeleteView.as_view(), name="delete_copy"),
    path("detailgenre/<int:pk>/delete", GenreDeleteView.as_view(), name="delete_genre"),
    path("detailauthor/<int:pk>/delete", AuthorDeleteView.as_view(), name="delete_author"),
    path("detailpublication/<int:pk>/delete", PublicationDeleteView.as_view(), name="delete_publication"),
    path("detailcopy/<int:pk>/update", CopyUpdateView.as_view(), name="update_copy"),
    path("detailgenre/<int:pk>/update", GenreUpdateView.as_view(), name="update_genre"),
    path("detailauthor/<int:pk>/update", AuthorUpdateView.as_view(), name="update_author"),
    path("detailpublication/<int:pk>/update", PublicationUpdateView.as_view(), name="update_publication"),
    path("detailcopy/<int:pk>/", CopiesDetailView.as_view(), name="detail_copy"),
    path("detailgenre/<int:pk>/", GenreDetailView.as_view(), name="detail_genre"),
    path("detailauthor/<int:pk>/", AuthorDetailView.as_view(), name="detail_author"),
    path("detailpublication/<int:pk>/", PublicationDetailView.as_view(), name="detail_publication"),
    path("newcopy/", CopyCreateView.as_view(), name="new_copy"),
    path("newpublication/", PublicationCreateView.as_view(), name="new_publication"),
    path("newgenre/", GenreCreateView.as_view(), name="new_genre"),
    path("newauthor/", AuthorCreateView.as_view(), name="new_author"),
    path("publications/", PublicationListView.as_view(), name="publications"),
    path("authors/", AuthorListView.as_view(), name="authors"),
    path("copies/", CopiesListView.as_view(), name="copies"),
    path("genres/", GenreListView.as_view(), name="genres"),
    path("", HomePageView, name="home")
]

library/models.py
from django.db import models
from django.urls import reverse

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    date_of_death = models.DateField()

    def __str__(self):
        return self.first_name + " " + self.last_name
    
    def get_absolute_url(self):
        return reverse("detail_author", kwargs={"pk": self.pk})

class Genre(models.Model):
    genre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.genre
    
    def get_absolute_url(self):
        return reverse("detail_genre", kwargs={"pk": self.pk})

class Publication(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    summary = models.TextField(max_length=250)
    isbn = models.CharField(max_length=13)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + " by " + str(self.author) + " (ISBN: " + self.isbn + ")"
    
    def get_absolute_url(self):
        return reverse("detail_publication", kwargs={"pk": self.pk})

class Book(models.Model):
    book = models.ForeignKey(Publication, on_delete=models.CASCADE)
    imprint = models.CharField(max_length=250)
    date_added = models.DateTimeField(auto_now_add=True)
    STATUS_CHOICES = [
        ('available', ('Available to borrow')),
        ('borrowed', ('Borrowed by someone')),
        ('archived', ('Archived - no longer available'))
    ]
    status = models.CharField(max_length=32, choices=STATUS_CHOICES)

    def __str__(self):
        return str(self.book) + " / Added: " + str(self.date_added) + " / Status: " + self.status
    
    def get_absolute_url(self):
        return reverse("detail_copy", kwargs={"pk": self.pk})

library/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Author, Book, Genre, Publication

# Homepage
def HomePageView(request):
    publication_count = Publication.objects.count()
    copies_count = Book.objects.count()
    copies_available_count = Book.objects.filter(status="available").count()
    author_count = Author.objects.count()
    genre_count = Genre.objects.count()
    context = {
        'publications': publication_count,
        'copies': copies_count,
        'copies_available': copies_available_count,
        'authors': author_count,
        'genres': genre_count 
    }
    template_name = "home.html"
    return render(request, template_name, context)

# List views
class PublicationListView(ListView):
    model = Publication
    template_name = "publication_list.html"

class AuthorListView(ListView):
    model = Author
    template_name = "author_list.html"

class GenreListView(ListView):
    model = Genre
    template_name = "genre_list.html"

class CopiesListView(ListView):
    model = Book
    template_name = "copy_list.html"

# Create views
class AuthorCreateView(CreateView):
    model = Author
    template_name = "author_new.html"
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]

class GenreCreateView(CreateView):
    model = Genre
    template_name = "genre_new.html"
    fields = ["genre"]

class PublicationCreateView(CreateView):
    model = Publication
    template_name = "publication_new.html"
    fields = ["title", "author", "summary", "isbn", "genre"]

class CopyCreateView(CreateView):
    model = Book
    template_name = "copy_new.html"
    fields = ["book", "imprint", "status"]

# Detail views
class PublicationDetailView(DetailView):
    model = Publication
    template_name = "publication_detail.html"

class AuthorDetailView(DetailView):
    model = Author
    template_name = "author_detail.html"

class GenreDetailView(DetailView):
    model = Genre
    template_name = "genre_detail.html"

class CopiesDetailView(DetailView):
    model = Book
    template_name = "copy_detail.html"

# Update views
class AuthorUpdateView(UpdateView):
    model = Author
    template_name = "author_update.html"
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]

class GenreUpdateView(UpdateView):
    model = Genre
    template_name = "genre_update.html"
    fields = ["genre"]

class PublicationUpdateView(UpdateView):
    model = Publication
    template_name = "publication_update.html"
    fields = ["title", "author", "summary", "isbn", "genre"]

class CopyUpdateView(UpdateView):
    model = Book
    template_name = "copy_update.html"
    fields = ["book", "imprint", "status"]

# Delete views
class PublicationDeleteView(DeleteView):
    model = Publication
    template_name = "publication_delete.html"
    success_url = reverse_lazy("home")

class AuthorDeleteView(DeleteView):
    model = Author
    template_name = "author_delete.html"
    success_url = reverse_lazy("home")

class GenreDeleteView(DeleteView):
    model = Genre
    template_name = "genre_delete.html"
    success_url = reverse_lazy("home")

class CopyDeleteView(DeleteView):
    model = Book
    template_name = "copy_delete.html"
    success_url = reverse_lazy("home")

library/templates/author_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete author</h1>
<form action=""  method="post">{% csrf_token%}
    <p>Are you sure you want to delete "{{ author.first_name }} {{author.last_name}}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

library/templates/author_detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <h2>{{ author.first_name }} {{ author.last_name }}</h2>
    <h3>{{ author.date_of_birth }} to {{ author.date_of_death }}</h3>
</div>

<a href="{% url 'update_author' author.pk %}">Update</a> | <a href="{% url 'delete_author' author.pk %}">Delete</a>

{% endblock content %}

library/templates/author_list.html
{% extends 'base.html' %}

{% block content %}
{% for author in author_list %}
<ul>
    <li>
        <a href="{% url 'detail_author' author.pk %}">
            {{author.first_name }} {{author.last_name}}: {{author.date_of_birth}} to {{author.date_of_death}}
        </a>
    </li>
</ul>
{% endfor %}
{% endblock content %}

library/templates/author_new.html
{% extends 'base.html' %}

{% block content %}
<h3>Add author</h3>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Tracker</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div id="left-panel">
        <div id="top-nav">
            <ul class="nav-list">
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'publications' %}">All publications</a></li>
                <li><a href="{% url 'authors' %}">All authors</a></li>
                <li><a href="{% url 'genres' %}">All genres</a></li>
                <li><a href="{% url 'copies' %}">All copies</a></li>
            </ul>
        </div>
        <div id="bottom-nav">
            <ul class="nav-list">
                <li><a href="{% url 'new_publication' %}">Add new publication</a></li>
                <li><a href="{% url 'new_author' %}">Add new author</a></li>
                <li><a href="{% url 'new_genre' %}">Add new genre</a></li>
                <li><a href="{% url 'new_copy' %}">Add new copy</a></li>
            </ul>
        </div>
    </div>
    <div id="right-panel">
        <h1>Book Tracker</h1>
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

library/templates/copy_list.html
{% extends 'base.html' %}

{% block content %}
{% for copy in book_list %}
<ul>
    <li>
        <a href="{% url 'detail_copy' copy.pk %}">
            {{ copy.book }} ({{ copy.imprint }}) / Date added: {{ copy.date_added }} / Status: {{ copy.status }}
        </a>
    </li>
</ul>
{% endfor %}
{% endblock content %}

library/templates/copy_update.html
{% extends "base.html" %}

{% block content %}
<h1>Update copy</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Update">
</form>
{% endblock content %}

library/templates/genre_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete genre</h1>
<form action=""  method="post">{% csrf_token%}
    <p>Are you sure you want to delete "{{ genre.genre }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

library/templates/genre_new.html
{% extends 'base.html' %}

{% block content %}
<h3>Add genre</h3>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

library/templates/genre_update.html
{% extends "base.html" %}

{% block content %}
<h1>Update genre</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Update">
</form>
{% endblock content %}

library/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h2>Database statistics:</h2>
<ul>
    <li>Publications added: {{ publications }}</li>
    <li>Authors added: {{ authors }}</li>
    <li>Genres added: {{ genres }}</li>
    <li>Copies: {{ copies }}</li>
    <li>Copies available: {{ copies_available }}</li>
    
</ul>
{% endblock content %}

library/templates/publication_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete publication</h1>
<form action=""  method="post">{% csrf_token%}
    <p>Are you sure you want to delete "{{ publication.title }} by {{publication.author}}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

library/templates/publication_detail.html
{% extends "base.html" %}

{% block content %}
<div>
    <h2>{{ publication.title }}</h2>
    <h3>by {{ publication.author }}</h3>
    <p>Summary: {{ publication.summary }}</p>
    <p>ISBN: {{ publication.isbn }}</p>
</div>

<a href="{% url 'update_publication' publication.pk %}">Update</a> | <a href="{% url 'delete_publication' publication.pk %}">Delete</a>

{% endblock content %}

library/templates/publication_list.html
{% extends 'base.html' %}

{% block content %}
{% for publication in publication_list %}
<ul>
    <li>
        <a href="{% url 'detail_publication' publication.pk %}">
            {{ publication.title }} by {{ publication.author }} (ISBN: {{publication.isbn}} / Genre: {{publication.genre}}) / Summary: {{ publication.summary }}</li>
        </a>
</ul>
{% endfor %}
{% endblock content %}